services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: habittrackeruser
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: habittrackerdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habittrackeruser -d habittrackerdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: