server:
  port: 8080

spring:
  application:
    name: HabitTracker
  datasource:
    url: jdbc:postgresql://localhost:5432/habittrackerdb
    username: habittrackeruser
    password: pass123
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    serialization:
      indent_output: true
