spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/habittrackerdb"
    username: habittrackeruser
    password: pass123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
#    default-schema : ylab_schema